/**
 * Directe Amazon.nl-productpagina's (ASIN).
 * Prijzen handmatig bijgewerkt — controleer periodiek op Amazon.
 * Laatst gecontroleerd: 31 mei 2026 (priceAmount op productpagina).
 */
export const AMAZON_URLS = {
  ecoflowDelta2Max: {
    asin: "B0C4F83WTX",
    url: "https://www.amazon.nl/dp/B0C4F83WTX",
    image: "https://m.media-amazon.com/images/I/61Qregf0EYL._AC_SX679_.jpg",
    price: 1199,
    rating: 4.6,
    reviewCount: 281,
    capacityKwh: 2.048,
    powerW: 2400,
    powerPeakW: 3000,
    weight: "23 kg",
    name: "EcoFlow DELTA 2 Max",
  },
  ankerSolixC1000: {
    asin: "B0CGQZ7XSB",
    url: "https://www.amazon.nl/dp/B0CGQZ7XSB",
    image: "https://m.media-amazon.com/images/I/61c9mHiU6VL._AC_SX679_.jpg",
    price: 639.99,
    rating: 4.6,
    reviewCount: 162,
    capacityKwh: 1.056,
    powerW: 1800,
    weight: "13 kg",
    name: "Anker SOLIX C1000",
  },
  ecoflowDelta3Plus: {
    asin: "B0DFPW2Y2C",
    url: "https://www.amazon.nl/dp/B0DFPW2Y2C",
    image: "https://m.media-amazon.com/images/I/61zFEkVvTzL._AC_SX679_.jpg",
    price: 849,
    rating: 4.7,
    reviewCount: 196,
    capacityKwh: 1.024,
    powerW: 1800,
    powerPeakW: 3600,
    weight: "12 kg",
    name: "EcoFlow DELTA 3 Plus",
  },
  ecoflowRiver2Pro: {
    asin: "B0BFQD5RMJ",
    url: "https://www.amazon.nl/dp/B0BFQD5RMJ",
    image: "https://m.media-amazon.com/images/I/5196yGqksNL._AC_SX679_.jpg",
    price: 549,
    rating: 4.5,
    reviewCount: 120,
    capacityKwh: 0.768,
    powerW: 800,
    weight: "7,8 kg",
    name: "EcoFlow RIVER 2 Pro",
  },
  ankerSolixC300: {
    asin: "B0D62GMQ3F",
    url: "https://www.amazon.nl/dp/B0D62GMQ3F",
    image: "https://m.media-amazon.com/images/I/719Cax9utKL._AC_SX679_.jpg",
    price: 229,
    rating: 4.6,
    reviewCount: 85,
    capacityKwh: 0.288,
    powerW: 300,
    weight: "4,1 kg",
    name: "Anker Solix C300",
  },
  ecoflowDelta2: {
    asin: "B0CKN74TLD",
    url: "https://www.amazon.nl/dp/B0CKN74TLD",
    image: "https://m.media-amazon.com/images/I/51flNVzTtWL._AC_SL1500_.jpg",
    price: 599,
    rating: 4.6,
    reviewCount: 1262,
    capacityKwh: 1.024,
    powerW: 1800,
    weight: "12 kg",
    name: "EcoFlow DELTA 2",
  },
  ecoflowDelta3Classic: {
    asin: "B0GMCHYHQR",
    url: "https://www.amazon.nl/dp/B0GMCHYHQR",
    image: "https://m.media-amazon.com/images/I/6188xsKjUmL._AC_SL1500_.jpg",
    price: 599,
    rating: 4.6,
    reviewCount: 45,
    capacityKwh: 1.024,
    powerW: 1800,
    weight: "12,1 kg",
    name: "EcoFlow DELTA 3 Classic",
  },
  ecoflowDelta3: {
    asin: "B0DFPTTXYY",
    url: "https://www.amazon.nl/dp/B0DFPTTXYY",
    image: "https://m.media-amazon.com/images/I/51o6Ji27QDL._AC_SL1500_.jpg",
    price: 749,
    rating: 4.7,
    reviewCount: 80,
    capacityKwh: 1.024,
    powerW: 1800,
    weight: "12,5 kg",
    name: "EcoFlow DELTA 3",
  },
  jackeryExplorer1000V2: {
    asin: "B0DB1T34X5",
    url: "https://www.amazon.nl/dp/B0DB1T34X5",
    image: "https://m.media-amazon.com/images/I/61uB1kQXCML._AC_SL1500_.jpg",
    price: 559,
    rating: 4.6,
    reviewCount: 293,
    capacityKwh: 1.07,
    powerW: 1500,
    weight: "10,8 kg",
    name: "Jackery Explorer 1000 V2",
  },
  ecoflowRiver3Plus: {
    asin: "B0FLWBXSKK",
    url: "https://www.amazon.nl/dp/B0FLWBXSKK",
    image: "https://m.media-amazon.com/images/I/51GP8+vE8pL._AC_SL1000_.jpg",
    price: 299,
    rating: 4.5,
    reviewCount: 12,
    capacityKwh: 0.286,
    powerW: 600,
    weight: "4,7 kg",
    name: "EcoFlow RIVER 3 Plus",
  },
  jackeryExplorer2000V2: {
    asin: "B0DSK8DN8N",
    url: "https://www.amazon.nl/dp/B0DSK8DN8N",
    image: "https://m.media-amazon.com/images/I/71kH8xJqHQL._AC_SX679_.jpg",
    price: 949,
    rating: 4.6,
    reviewCount: 120,
    capacityKwh: 2.042,
    powerW: 2200,
    weight: "18 kg",
    name: "Jackery Explorer 2000 v2",
  },
} as const;

export type AmazonListingKey = keyof typeof AMAZON_URLS;
